### PR TITLE
Updated Framework files with bitcode generation

### PR DESCRIPTION
**Pull request by dantetwc**
The original frameworks do not come with bitcode and hence cannot be uploaded to app store. This commit contains updated frameworks with bitcode

### CODE REVIEW

**Comment by Looveh** [comment]
@dantetwc There's unfortunately merge conflicts that need be resolved. Also, we have successfully uploaded this library to App Store many times, are you sure this is the issue?

**Comment by MD3XTER** [comment]
He is referring to this #44 and I had the same issue until I haven't changed the current frameworks with @dantetwc suggested ones.

**Comment by BadClyx** [comment]
Hi, would it be possible to merge this PR ? I really need this PR to be able to publish on the app store. Thanks.

**Comment by Looveh** [comment]
Try installing v3.0.0 with CocoaPods, this will be the main supported way of integrating iOS moving forward and should resolve your issues with bitcode generation

**Pull request closed without merging**
