### PR TITLE
add alternativeAdvertisingNameEnabled param to startDFU

### PR DESCRIPTION
**Pull request by townofdon**
This makes `alternativeAdvertisingNameEnabled` configurable.

See reason for this [here](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/pull/160).

It looks like this param was only needed on iOS - as you can see the param in the Android file is unused. I didn't see a good way around this and am open to suggestions!

### CODE REVIEW

**Comment by Looveh** [comment]
Thanks for the contribution! Wouldn't it be possible to simply not extract the `alternativeAdvertisingNameEnabled` property on Android, to avoid making it misleading and document this property in the README?

**Comment by townofdon** [comment]
> Thanks for the contribution! Wouldn't it be possible to simply not extract the `alternativeAdvertisingNameEnabled` property on Android, to avoid making it misleading and document this property in the README?

That makes much more sense! Maybe something like this?

```
// index.js

...

if (Platform.OS === 'ios') {
  return return RNNordicDfu.startDFU(upperDeviceAddress, deviceName, filePath, alternativeAdvertisingNameEnabled);
}

return return RNNordicDfu.startDFU(upperDeviceAddress, deviceName, filePath);
```

And then in the Readme we could indicate that the `alternativeAdvertisingNameEnabled` param is ios-only. Thoughts?

**Comment by townofdon** [comment]
@Looveh Just updated PR with platform-specific `startDFU` calls. Let me know if it needs anything else!

**Comment by Looveh** [comment]
Looks good! Was this value `true` by default before, ie will this change any existing behavior?

**Comment by townofdon** [comment]
Yep! This value defaults to `true` in the swift file:

https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/DFUServiceInitiator.swift#L191

So unless the user explicitly passes `false` the behavior is unchanged.

**Comment by Looveh** [comment]
Great, thanks!

**Pull request merged**
